name: Encrypt and Publish to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production 

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Copiar assets
        run: |
          cp -r assets/* .

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: "npm"

      - name: Encrypt index.html
        run: |
          npx staticrypt index.html \
            --short true \
            -t password-template.html \
            -p "${{ secrets.STATICRYPT_PASSWORD }}"

          # Reemplazar el original por el encriptado
          mv encrypted/index.html index.html
          rm -rf encrypted
          # Eliminar template solo si existe
          [ -f password-template.html ] && rm password-template.html
          # Eliminar archivo de configuración de Staticrypt solo si existe
          [ -f .staticrypt.json ] && rm .staticrypt.json

      - name: Add CNAME (opcional si usas subdominio custom)
        run: |
          echo "${{ github.event.repository.name }}" > CNAME

      - name: Remove assets before deploy
        run: |
          rm -rf assets

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
